{
 "title": "Dashboard Grafana",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Свободное место",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=\"ext4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободная RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Утилизация CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}